targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: flutter_issue_tracker|lib/data/graphql/schema.docs.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: flutter_issue_tracker|lib/data/graphql/schema.docs.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: flutter_issue_tracker|lib/data/graphql/schema.docs.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: flutter_issue_tracker|lib/data/graphql/schema.docs.graphql
