name: flutter_issue_tracker
description: Flutter Issue Tracker App.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  ferry_flutter: ^0.4.0
  firebase_auth_oauth: ^0.2.4
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.2
  freezed_annotation: ^0.11.0+1
  gql_http_link: ^0.3.2
  jiffy: ^3.0.1
  line_awesome_icons: ^1.0.4+2
  loading_indicator: ^1.2.0
  multi_select_flutter: ^3.1.8
  responsive_framework: ^0.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  integration_test: ^1.0.2+2
  build_runner: ^1.10.0
  ferry_generator: ^0.3.3
  freezed: ^0.11.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_internet.png
    - assets/images/server_failure.png
    - assets/images/no_results.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
